### ISSUE TITLE
Timeline styling seems to be broken?

### ISSUE THREAD

**Issue by jreus** [b-camphart/timeline-view#12]
I'm just trying out this plugin again, and it seems like the styling is broken.

The controls for filtering, zooming, etc are displayed in a separate block above the timeline, instead of layered on top of it.

Here is a screenshot:

![Screenshot_20240226_180737](https://github.com/b-camphart/timeline-view/assets/1451059/b57773ab-56c5-4bcb-ac71-b977d3979f00)

**Comment by b-camphart** [comment]
Looks like you're using a custom theme.  Can you tell me which one?  There might be something in it that's forcing this to happen.

**Comment by jreus** [comment]
I was using the `minimal` theme. But even in the default theme this happens.

Here's an image of the timeline view with the default obsidian theme and all custom css snippets disabled.:

![Screenshot_20240227_115132](https://github.com/b-camphart/timeline-view/assets/1451059/903f66ba-35c4-4067-a6c3-f3474ecbb80d)

![Screenshot_20240227_115237](https://github.com/b-camphart/timeline-view/assets/1451059/1608b9ac-f2aa-4719-8b55-e3a86c41eedd)

**Comment by b-camphart** [comment]
Ok, that's odd.  I use minimal myself, and have tested it with both (classic developer "it works on my machine").  Do you have any css snippets enabled?

**Comment by jreus** [comment]
I did a full reinstallation of obsidian and it seems to be working now. I have no idea what the issue was, but thanks for trying to give some support!

**Comment by b-camphart** [comment]
Let me know if you run into this again as you install other plugins.  I made it closely tied to the styling of obsidian so that it would match whatever themes are applied, but that also means other themes/plugins can erroneously change the way it looks if they're designed to change something in obsidian.

I'll close this for now.
