### ISSUE TITLE
Enhancement of navigating in the timeline. 

### ISSUE THREAD

**Issue by Jo55Jo** [b-camphart/timeline-view#13]
First of all, thank you for this amazing project. I believe it to be a great improvement for my history research in the future. However, at the moment there are still some issues I face. 

- If I select a property all the other notes not belonging are still displayed at the moment. 
- If I select a property the groups colors start bugging. 

Also: 
It would be great if one could use the arrow keys to navigate forward and backwards in time. 

I am also very much looking forward for new layouts and ways to visualize Data. The current one is already pretty nice but an Option where one can read the name of the note would be also quiet helpful. Maybe this will be possible in the vertical view?

**Comment by b-camphart** [comment]
Can you describe how the group colors start bugging when you select a new property?

I like the idea of being able to toggle notes without the property being visible (though, you can also use a filter to accomplish this for now).

Arrow navigation is a good idea too, I'll add it to the roadmap :)

Thanks for the suggestions!

**Comment by b-camphart** [comment]
@Jo55Jo I've split this up into separate tickets to more easily track everything.  Going to close this one.  Thank you again for the suggestions!
