### ISSUE TITLE
Follow active note feature

### ISSUE THREAD

**Issue by jordanmills** [b-camphart/timeline-view#14]
It would be great if there were an option to have the timeline entry for the currently active note highlighted or zoomed to or something like that.

**Comment by a-oneil** [comment]
+1

**Comment by b-camphart** [comment]
Will be in 1.2.0

It will work by linking the tab to another.  Every time you navigate to a new note, the timeline will focus on the note within the timeline (if it's not filtered out).  Also, clicking on a note from within the timeline will open that note in the linked tab.

**Comment by jordanmills** [comment]
Love the quick response.  Thank you!
