### ISSUE TITLE
Plugin is too slow

### ISSUE THREAD

**Issue by anareaty** [b-camphart/timeline-view#8]
This plugin is super slow if you have more then a few notes in the vault. I have about 2000 notes in my vault, and this plugin takes ages to open. It don't seem to be useful until it is improved.

**Comment by b-camphart** [comment]
I was curious about this.  I have some ideas for improving the performance.  Thanks for the feedback!

**Comment by b-camphart** [comment]
@anareaty can you take a look at v1.0.1 and let me know if the performance is still bad?  I think I solved the main problem, but there's more I could potentially do, if it's still unusable.

**Comment by KuiyueRO** [comment]
I have 6k notes and it's very slow :) but I like this plugin very much.

**Comment by b-camphart** [comment]
Hey @KuiyueRO thank you for the feedback!  Still very early days, so I'll be working to make it more stable as fast as I can.  Have you tried version 1.0.1?  Is it still slow?

**Comment by KuiyueRO** [comment]
Yes, it's still slow. These notes span about two years.

**Comment by KuiyueRO** [comment]
It's really smooth, thank you！
