### ISSUE TITLE
Properties from YAML are not displayed in the list

### ISSUE THREAD

**Issue by Fertion** [b-camphart/timeline-view#9]
Only the basic properties "created" and "modified" are displayed in the list. The other properties are not in the list.

![image](https://github.com/b-camphart/timeline-view/assets/102726751/a9ccabf3-547c-4dca-94f5-c6a394d3a0c1)

**Comment by AlexKoenig1** [comment]
I have the same issue :(

**Comment by b-camphart** [comment]
These are properties you already have in your vault?  Or are they new properties you've defined after opening the plugin?  Also, what version of obsidian are you using?  All this info will help me figure out where the issue is 🙂

**Comment by Fertion** [comment]
> These are properties you already have in your vault? Or are they new properties you've defined after opening the plugin? Also, what version of obsidian are you using? All this info will help me figure out where the issue is 🙂

Most of the properties have been in my files for a long time. Some of them were created after installing the plugin for testing.
Restarting does not help in any way.

The obsidian version is 1.4.16, same as the installer version.

If it matters, I have a pretty big vault, 6380 notes.

**Comment by jreus** [comment]
I have the same issue.

**Comment by jreus** [comment]
I've been getting this error in the dev console associated with timeline view.
Could this have something to do with the issue of not being able to filter by custom yaml properties?

```
plugin:timeline-view:106 
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/home/xxx/obsidianvault//.obsidian/types.json'
```

**Comment by b-camphart** [comment]
I think these are two separate issues.  Most properties aren't visible to the plugin unless they've been explicitly defined - I'll have to see if there's a way to ask obsidian for properties that haven't.

@jreus what OS are you on?  My guess is that the way the plugin is checking for explicitly defined types doesn't quite work on your machine properly, which I'm pretty sure I can fix quickly and easily.

**Comment by b-camphart** [comment]
@Fertion @jreus @AlexKoenig1 can you update to 1.1.1 and let me know if it fixes the issue?

**Comment by Fertion** [comment]
![image](https://github.com/b-camphart/timeline-view/assets/102726751/5f1cf4ce-3e3e-45ef-a698-16b13e502b08)
It won't install for some reason

**Comment by b-camphart** [comment]
Try it now :) 
I did something dumb with my version naming.  Should be able to install now.
